name: 'MDL Z80 Optimizer'
description: 'Optimize Z80/z80n/z180 assembler code'
author: 'santiontanon'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  args: 
    description: 'Command options to pass (as array / list)'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/santiontanon/mdlz80optimizer:master'
  args: ${{ inputs.args }}
