; Test case: see if macro expansions with labels work as expected (notice that the code generated by thsi will be garbage, but it's ok, it's just a test)

mymacro: macro ?basemacro
base: ?basemacro
	or a
	jr z,macrolabel2
macrolabel1:
	ld b,1
	jr macrolabel3
macrolabel2:
	ld b,2
macrolabel3:
	ld a,(base.data)
	endm


	mymacro mymacro2
label1:
	push bc
expansion_name:	mymacro mymacro2
label2:
	push bc
label3:
	mymacro mymacro3
	push bc

	ld (var),a

	REPT 4
loop:
	nop
endloop:
	ENDM

end:
	jp end

var:
	db 0

mymacro2: macro
data:
	db 1
	endm

mymacro3: macro
data:
	db 2
	endm


