/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workers.searchopt;

import cl.MDLConfig;
import code.CPUOp;
import code.CPUOpDependency;
import code.CodeBase;
import code.CodeStatement;
import code.Expression;
import code.SourceFile;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import parser.SourceLine;
import util.microprocessor.IMemory;
import util.microprocessor.PlainZ80IO;
import util.microprocessor.PlainZ80Memory;
import util.microprocessor.Z80.CPUConfig;
import util.microprocessor.Z80.CPUConstants.RegisterNames;
import util.microprocessor.Z80.Z80Core;
import workers.MDLWorker;

/**
 *
 * @author santi
 */
public class SearchBasedOptimizer implements MDLWorker {
    public static final int SEARCH_ID_OPS = 0;
    public static final int SEARCH_ID_BYTES = 1;
    
    MDLConfig config;
    boolean trigger = false;
    boolean showNewBestDuringSearch = true;
    
    int numberOfRandomSolutionChecks = 1000;
    int searchType = SEARCH_ID_OPS;
        
    public static class SolutionRecord {
        // current search state:
        List<CPUOp> ops = new ArrayList<>();
        // The "dependencies" array, contains the set of dependencies (Registers/flags) that
        // have already been set by previous instructions:
        boolean dependencies[] = null;
        
        long solutionsEvaluated = 0;
        
        // best solution:
        List<CPUOp> bestOps = null;
        int bestSize = 0;
        int bestTime = 0;
    }
    
    
    public SearchBasedOptimizer(MDLConfig a_config)
    {
        config = a_config;
    }
    
    
    @Override
    public String docString() {
        return "- ```-so```: Runs the search-based-based optimizer (input file is a function specification instead of an assembler file).\n";
    }

    
    @Override
    public String simpleDocString() {
        return "- ```-so```: Runs the search-based-based optimizer (input file is a function specification instead of an assembler file).\n";
    }

    
    @Override
    public boolean parseFlag(List<String> flags) {
        if (flags.get(0).equals("-so")) {
            flags.remove(0);
            trigger = true;
            config.codeSource = MDLConfig.CODE_FROM_SEARCHBASEDOPTIMIZER;
            return true;
        }
        return false;    
    }

    
    @Override
    public boolean triggered() {
        return trigger;
    }

    
    @Override
    public boolean work(CodeBase code) {
        // Parse specification file:
        Specification spec = SpecificationParser.parse(config.inputFile, code, config);
        if (spec == null) {
            config.error("Cannot parse the input specification file '"+config.inputFile+"'");
            return false;
        }
                
        SourceFile sf = new SourceFile("autogenerated.asm", null, null, code, config);
        code.addOutput(null, sf, 0);

        // Precompute all the op dependencies before search:
        List<CPUOpDependency> allDependencies = new ArrayList<>();
        for(String regName: new String[]{"A", "F", "B", "C", "D", "E", "H", "L", 
                                         "IXH", "IXL", "IYH", "IYL"}) {
            CPUOpDependency dep = new CPUOpDependency(regName, null, null, null, null);
            allDependencies.add(dep);
        }
//        for(String flagName: new String[]{"S" ,"Z" ,"H" , "P/V" ,"N" , "C"}) {
        for(String flagName: new String[]{"S" ,"Z", "C"}) {
            CPUOpDependency dep = new CPUOpDependency(null, flagName, null, null, null);
            allDependencies.add(dep);
        }
        config.debug("allDependencies: " + allDependencies.size());
        
        // Run the search process to generate code:
        List<SBOCandidate> candidateOps = precomputeCandidateOps(spec, allDependencies, code);
        if (candidateOps == null) return false;
        config.debug("candidateOps: " + candidateOps.size());
        
        // Create a simulator:
        PlainZ80Memory z80Memory = new PlainZ80Memory();
        
        // Search via iterative deepening:
        SolutionRecord sr = new SolutionRecord();
        sr.dependencies = spec.getInitialDependencies(allDependencies);
        config.debug("Initial dependency set: " + Arrays.toString(sr.dependencies));
        if (searchType == SEARCH_ID_OPS) {
            for(int depth = 1; depth<=spec.maxDepth; depth++) {
                if (depthFirstSearch(depth, 0x10000,
                                     candidateOps, 
                                     spec, code, 
                                     spec.codeStartAddress, z80Memory,
                                     sr)) {
                    // solution found!
                    break;
                }
                config.info("SearchBasedOptimizer: depth "+depth+" complete ("+sr.solutionsEvaluated+" solutions tested)");
            }

        } else if (searchType == SEARCH_ID_BYTES) {
            for(int size = 1; size<=spec.maxSizeInBytes; size++) {
                System.out.println(size);
                if (depthFirstSearch(0x10000, spec.codeStartAddress + size,
                                     candidateOps, 
                                     spec, code, 
                                     spec.codeStartAddress, z80Memory,
                                     sr)) {
                    // solution found!
                    break;
                }
                config.info("SearchBasedOptimizer: size "+size+" complete ("+sr.solutionsEvaluated+" solutions tested)");
            }

        } else {
            config.error("Unsupported search type " + searchType);
            return false;
        }

        if (sr.bestOps == null) return false;
        
        int lineNumber = 1;
        for(CPUOp op:sr.bestOps) {
            SourceLine sl = new SourceLine("    " + op.toString(), sf, lineNumber);
            CodeStatement s = new CodeStatement(CodeStatement.STATEMENT_CPUOP, sl, sf, config);
            s.op = op;
            sf.getStatements().add(s);
            lineNumber++;
        }
        
        config.info("SearchBasedOptimizer: search ended ("+sr.solutionsEvaluated+" solutions tested)");
                
        return true;
    }
    
    
    List<SBOCandidate> precomputeCandidateOps(Specification spec, List<CPUOpDependency> allDependencies, CodeBase code)
    {
        List<SBOCandidate> candidates = new ArrayList<>();
        
        /*
        OK - AND/OR/XOR
        OK - INC/DEC
        OK - ADD/ADC/SUB/SBC
        OK - LD
        OK - RLCA/RLA/RRCA/RRA/RLC/RL/RRC/RR
        OK - SLA/SRA/SRL/SLI
        - CPL/NEG
        - CCF/SCF
        - PUSH/POP
        - EX/EXX
        - LDI/LDD/LDIR/LDDR
        - CPI/CPD/CPIR/CPDR
        - CP
        - DAA
        - HALT/DI/EI/IM
        - RLD/RRD
        - BIT/SET/RES
        - JP/JR/DJNZ
        - CALL/RET/RETI/RETN
        - RST
        - IN/INI/IND/INIR/INDR
        - OUT/OUTI/OUTD/OTIR/OTDR
        - NOP
        */
        
        if (spec.allowAndOrXorOps) {
            if (!precomputeAndOrXor(candidates, spec, allDependencies, code)) return null;
        }
        if (spec.allowIncDecOps) {
            if (!precomputeIncDec(candidates, spec, allDependencies, code)) return null;
        }
        if (spec.allowAddAdcSubSbc) {
            if (!precomputeAddAdcSubSbc(candidates, spec, allDependencies, code)) return null;
        }
        if (spec.allowLd) {
            if (!precomputeLd(candidates, spec, allDependencies, code)) return null;
        }
        if (spec.allowRotations) {
            if (!precomputeRotations(candidates, spec, allDependencies, code)) return null;
        }
        if (spec.allowShifts) {
            if (!precomputeShifts(candidates, spec, allDependencies, code)) return null;
        }
        
        return candidates;
    }
    
    
    boolean precomputeOp(String line, List<SBOCandidate> candidates, List<CPUOpDependency> allDependencies, CodeBase code)
    {
        List<String> tokens = config.tokenizer.tokenize(line);
        SourceFile sf = new SourceFile("dummy", null, null, code, config);
        SourceLine sl = new SourceLine(line, sf, 0);
        List<CodeStatement> l = config.lineParser.parse(tokens, sl, sf, null, code, config);
        if (l == null || l.size() != 1) {
            config.error("Parsing candidate op in the search-based optimizer resulted in none, or more than one op! " + line);
            return false;
        }
        CodeStatement s = l.get(0);
        SBOCandidate candidate = new SBOCandidate(s.op, allDependencies, code, config);
        if (candidate.bytes == null) return false;
        candidates.add(candidate);
        return true;
    }
    
    
    boolean precomputeAndOrXor(List<SBOCandidate> candidates, Specification spec, 
                               List<CPUOpDependency> allDependencies, CodeBase code)
    {
        String opNames[] = {"and", "or", "xor"};
        String regNames[] = {"a", "b", "c", "d", "e", "h", "l"};
        for(String opName : opNames) {
            // register argument:
            for(String regName : regNames) {
                String line = opName + " " + regName;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            
            // constant argument:
            for(Integer constant:spec.allowed8bitConstants) {
                String line = opName + " " + constant;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;                
            }
            
            // (hl):
            if (spec.allowRamUse) {
                String line = opName + " (hl)";
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
            }
            
            // (ix+d) / (iy+d):
            if (spec.allowRamUse) {
                for(String reg:new String[]{"ix","iy"}) {
                    for(Integer constant:spec.allowedOffsetConstants) {
                        if (constant >= 0) {
                            String line = opName + " ("+reg+"+"+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        } else {
                            String line = opName + " ("+reg+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        }
                    }
                }
            }
        }
        return true;
    }
    

    boolean precomputeIncDec(List<SBOCandidate> candidates, Specification spec, 
                             List<CPUOpDependency> allDependencies, CodeBase code)
    {
        String opNames[] = {"inc", "dec"};
        String regNames[] = {"a", "b", "c", "d", "e", "h", "l",
                             "bc", "de", "hl", 
                             "ix", "iy",
                             "ixh", "ixl", "iyh", "iyl"};
        for(String opName : opNames) {
            // register argument:
            for(String regName : regNames) {
                String line = opName + " " + regName;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            
            // (hl):
            if (spec.allowRamUse) {
                String line = opName + " (hl)";
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
            }
            
            // (ix+d) / (iy+d):
            if (spec.allowRamUse) {
                for(String reg:new String[]{"ix","iy"}) {
                    for(Integer constant:spec.allowedOffsetConstants) {
                        if (constant >= 0) {
                            String line = opName + " ("+reg+"+"+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        } else {
                            String line = opName + " ("+reg+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        }
                    }
                }        
            }
        }
        return true;
    }
    
    
    boolean precomputeAddAdcSubSbc(List<SBOCandidate> candidates, Specification spec, 
                                   List<CPUOpDependency> allDependencies, CodeBase code)
    {
        String opNames[] = {"add", "adc", "sub", "sbc"};
        String regNames[] = {"a", "b", "c", "d", "e", "h", "l", "ixh", "ixl", "iyh", "iyl"};
        for(String opName : opNames) {
            // register argument:
            for(String regName : regNames) {
                String line = opName + " a," + regName;
                if (opName.equals("sub") && regName.startsWith("i")) continue;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            
            // constant argument:
            for(Integer constant:spec.allowed8bitConstants) {
                String line = opName + " a," + constant;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;                
            }
            
            // (hl):
            if (spec.allowRamUse) {
                String line = opName + " a,(hl)";
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
            }
            
            // (ix+d) / (iy+d):
            if (spec.allowRamUse) {
                for(String reg:new String[]{"ix","iy"}) {
                    for(Integer constant:spec.allowedOffsetConstants) {
                        if (constant >= 0) {
                            String line = opName + " a,("+reg+"+"+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        } else {
                            String line = opName + " a,("+reg+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        }
                    }
                }
            }
        }
        
        String ops16bit[] = {"add hl,bc", "add hl,de", "add hl,hl", "add hl,sp",
                             "add ix,bc", "add ix,de", "add ix,ix", "add ix,sp",
                             "add iy,bc", "add iy,de", "add iy,iy", "add iy,sp",
        
                             "adc hl,bc", "adc hl,de", "adc hl,hl", "adc hl,sp",
                             "sbc hl,bc", "sbc hl,de", "sbc hl,hl", "sbc hl,sp"};
        for(String line:ops16bit) {
            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
        }
        return true;
    }    
    
    
    boolean precomputeLd(List<SBOCandidate> candidates, Specification spec, 
                         List<CPUOpDependency> allDependencies, CodeBase code)
    {
        String regNames[] = {"a", "b", "c", "d", "e", "h", "l"};
        for(String arg1 : regNames) {
            for(String arg2 : regNames) {
                if (arg1.equals(arg2)) continue;
                String line = "ld " + arg1 + "," + arg2;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            if (spec.allowRamUse) {
                String line = "ld (hl)," + arg1;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
                line = "ld " + arg1 + ",(hl)";
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            
            // constant argument:
            for(Integer constant:spec.allowed8bitConstants) {
                String line = "ld " + arg1 + "," + constant;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;                
            }
            
            // (ix+d) / (iy+d):
            if (spec.allowRamUse) {
                for(String reg:new String[]{"ix","iy"}) {
                    for(Integer constant:spec.allowedOffsetConstants) {
                        if (constant >= 0) {
                            String line = "ld " + arg1 + ",("+reg+"+"+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                            line = "ld ("+reg+"+"+constant+")," + arg1;
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        } else {
                            String line = "ld " + arg1 + ",("+reg+constant+")";
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;
                            line = "ld ("+reg+constant+")," + arg1;
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;
                        }
                    }
                }
            }
        }
        
        String regNames2[] = {"a", "b", "c", "d", "e"};
        String regNames3[] = {"ixh", "ixl", "iyh", "iyl"};
        for(String arg1 : regNames2) {
            for(String arg2 : regNames3) {
                String line = "ld " + arg1 + "," + arg2;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
        }
        for(String arg1 : regNames3) {
            for(String arg2 : regNames2) {
                String line = "ld " + arg1 + "," + arg2;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
        }
        
        // ld (hl)/ixh/ixl/iyh/iyl,n:
        {
            String args[] = {"ixh", "ixl", "iyh", "iyl"};
            for(String  arg1:args) {
                for(Integer constant:spec.allowed8bitConstants) {
                    String line = "ld " + arg1 + "," + constant;
                    if (!precomputeOp(line, candidates, allDependencies, code)) return false;                
                }
            }
        }
        
        if (spec.allowRamUse) {
            for(Integer constant:spec.allowed8bitConstants) {
                String line = "ld (hl)," + constant;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;                
            }
        }
        
//        if (spec.allowRamUse) {
            // ld (nn),a/bc/de/hl/ix/iy/sp
            // ...
        
            // ld a/bc/de/hl/ix/iy/sp,(nn)
            // ...            
//        }

        // ld (ix+o)/(iy+o),n
        if (spec.allowRamUse) {
            for(Integer constant:spec.allowed8bitConstants) {
                for(String reg:new String[]{"ix","iy"}) {
                    for(Integer offset:spec.allowedOffsetConstants) {
                        if (constant >= 0) {
                            String line = "ld ("+reg+"+"+offset+")," + constant;
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        } else {
                            String line = "ld ("+reg+offset+")," + constant;
                            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                        }
                    }
                }
            }
        }

        // ld bc/de/hl/sp/ix/iy,nn
        {
            String args[] = {"bc", "de", "hl", "sp", "ix", "iy"};
            for(String  arg1:args) {
                for(Integer constant:spec.allowed16bitConstants) {
                    String line = "ld " + arg1 + "," + constant;
                    if (!precomputeOp(line, candidates, allDependencies, code)) return false;                
                }
            }
        }
        
        String otherOps[] = {//"ld a,i", "ld a,r", "ld i,a", "ld r,a",
                             //"ld sp,hl", "ld sp,ix", "ld sp,iy",
                             "ld ixl,ixh", "ld ixh,ixl", 
                             "ld iyl,iyh", "ld iyh,iyl",
                             };
        for(String line:otherOps) {
            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
        }
        if (spec.allowRamUse) {
            String otherRamOps[] = {"ld (bc),a", "ld (de),a",
                                    "ld a,(bc)", "ld a,(de)"};
            for(String line:otherRamOps) {
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
            }            
        }
        return true;
    }
    
    
    boolean precomputeRotations(List<SBOCandidate> candidates, Specification spec, 
                                List<CPUOpDependency> allDependencies, CodeBase code)
    {
        String opNames[] = {"rlc", "rl", "rrc", "rr"};
        String regNames[] = {"a", "b", "c", "d", "e", "h", "l"};
        for(String op : opNames) {
            for(String reg : regNames) {
                String line = op + " " + reg;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            if (spec.allowRamUse) {
                String line = op + " (hl)";
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            
            // (ix+o)/(iy+o):
            for(String reg:new String[]{"ix","iy"}) {
                for(Integer constant:spec.allowedOffsetConstants) {
                    if (constant >= 0) {
                        String line = op + " ("+reg+"+"+constant+")";
                        if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                    } else {
                        String line = op + " ("+reg+constant+")";
                        if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                    }
                }
            }        
        }        
        String otherOps[] = {"rlca", "rla", "rrca", "rra"};
        for(String line:otherOps) {
            if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
        }
        return true;
    }


    boolean precomputeShifts(List<SBOCandidate> candidates, Specification spec, 
                             List<CPUOpDependency> allDependencies, CodeBase code)
    {
        String opNames[] = {"sla", "sra", "srl", "sli"};
        String regNames[] = {"a", "b", "c", "d", "e", "h", "l"};
        for(String op : opNames) {
            for(String reg : regNames) {
                String line = op + " " + reg;
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            if (spec.allowRamUse) {
                String line = op + " (hl)";
                if (!precomputeOp(line, candidates, allDependencies, code)) return false;
            }
            
            // (ix+o)/(iy+o):
            for(String reg:new String[]{"ix","iy"}) {
                for(Integer constant:spec.allowedOffsetConstants) {
                    if (constant >= 0) {
                        String line = op + " ("+reg+"+"+constant+")";
                        if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                    } else {
                        String line = op + " ("+reg+constant+")";
                        if (!precomputeOp(line, candidates, allDependencies, code)) return false;            
                    }
                }
            }   
        }        
        return true;
    }
    
    
    boolean depthFirstSearch(int depth, int codeMaxAddress, 
                             List<SBOCandidate> candidateOps, 
                             Specification spec, CodeBase code,
                             int codeAddress, IMemory z80Memory,
                             SolutionRecord sr)
    {
        if (depth == 0 || codeAddress >= codeMaxAddress) {
            try {
                sr.solutionsEvaluated++;
                
//                if (sr.ops.size() == 1) {
//                    config.debug("" + sr.ops);
//                }
                
                int time = 0;
                for(int i = 0; i < numberOfRandomSolutionChecks; i++) {
                    time = evaluateSolution(codeAddress, z80Memory, spec, code);
                    if (time < 0) return false;
                }
                int size = codeAddress - spec.codeStartAddress;
                if (sr.bestOps == null || 
                    size < sr.bestSize ||
                    (size == sr.bestSize && time < sr.bestTime) ||
                    (size == sr.bestSize && time == sr.bestTime && sr.ops.size() < sr.bestOps.size())) {
                    sr.bestOps = new ArrayList<>();
                    sr.bestOps.addAll(sr.ops);
                    sr.bestSize = size;
                    sr.bestTime = time;
                    
                    if (showNewBestDuringSearch) {
                        config.info("New solution found after "+sr.solutionsEvaluated+" solutions tested (size: "+size+", time: " + time + "):");
                        for(CPUOp op:sr.bestOps) {
                            config.info("    " + op);
                        }
                    }
                }
                return true;
            } catch(Exception e) {
                // This could happen if the program self-modifies itself and garbles the codebase,
                // resulting in an inexisting opcode!
//                config.error("Something went wrong during solution execution in the z80 simulator: " + e.getMessage());
//                config.error("StackTrace: " + Arrays.toString(e.getStackTrace()));
//                config.error("program: " + sr.ops);
//                for(int i = spec.codeStartAddress;i<codeAddress;i++) {
//                    config.error(config.tokenizer.toHex(z80Memory.readByte(i), 2));
//                }
                return false;
            }
        } else {
            boolean found = false;
            for(SBOCandidate candidate : candidateOps) {
                boolean dependenciesSatisfied = true;
                for(int i = 0;i<sr.dependencies.length;i++) {
                    if (candidate.inputDependencies[i] && !sr.dependencies[i]) {
                        dependenciesSatisfied = false;
                        break;
                    }
                }
                if (codeAddress + candidate.bytes.length <= codeMaxAddress &&
                    dependenciesSatisfied) {                
                    int nextAddress = codeAddress;
                    for(int i = 0; i < candidate.bytes.length; i++) {
                        z80Memory.writeByte(nextAddress, candidate.bytes[i]);
                        nextAddress++;
                    }
                    sr.ops.add(candidate.op);
                    
                    boolean previousDependencies[] = new boolean[sr.dependencies.length];
                    for(int i = 0;i<sr.dependencies.length;i++) {
                        previousDependencies[i] = sr.dependencies[i];
                        if (candidate.outputDependencies[i]) sr.dependencies[i] = true;
                    }                    
                    if (depthFirstSearch(depth-1, codeMaxAddress, 
                                         candidateOps, spec, code, nextAddress, z80Memory, sr)) {
                        found = true;
                        // we keep going, in case we find a solution of the same size, but faster
                    }
                    for(int i = 0;i<sr.dependencies.length;i++) {
                        sr.dependencies[i] = previousDependencies[i];
                    }
                    sr.ops.remove(sr.ops.size()-1);
                }
            }
            return found;
        }
    }
    
    
    // return -1 is solution fails
    // return time it takes if solution succeeds
    int evaluateSolution(int breakPoint, IMemory z80Memory, 
                         Specification spec, CodeBase code) throws Exception
    {
        // evaluate solution:
        Random rand = new Random();
        Z80Core z80 = new Z80Core(z80Memory, new PlainZ80IO(), new CPUConfig(config));
        z80.reset();

        // randomize the register contents:
        RegisterNames eightBitRegisters[] = {
            RegisterNames.A, RegisterNames.F,
            RegisterNames.B, RegisterNames.C,
            RegisterNames.D, RegisterNames.E,
            RegisterNames.H, RegisterNames.L,
            RegisterNames.A_ALT, RegisterNames.F_ALT,
            RegisterNames.B_ALT, RegisterNames.C_ALT,
            RegisterNames.D_ALT, RegisterNames.E_ALT,
            RegisterNames.H_ALT, RegisterNames.L_ALT,
            RegisterNames.IXH, RegisterNames.IXL,
            RegisterNames.IYH, RegisterNames.IYL,
            RegisterNames.R
        };
        for(RegisterNames register: eightBitRegisters) {
            z80.setRegisterValue(register, rand.nextInt(256));
        }
        z80.setProgramCounter(spec.codeStartAddress);
                         
        // randomize constants:
        for(InputParameter parameter:spec.parameters) {
            int value = parameter.minValue + rand.nextInt((parameter.maxValue - parameter.minValue)+1);
            parameter.symbol.exp = Expression.constantExpression(value, config);
            parameter.symbol.clearCache();            
        }
        
        // randomize the memory contents:
        // ...
        
        // execute initial state:
        if (!spec.initCPU(z80, code)) {
            return -1;
        }
        
        while(z80.getProgramCounter() < breakPoint && 
              z80.getTStates() < spec.maxSimulationTime) {
            z80.executeOneInstruction();
        }
        
        // check if the solution worked:
        if (spec.checkGoalState(z80, z80Memory, code)) {
            return (int)z80.getTStates();
        } else {
            return -1;
        }
    }
}
